web/router.ex
defmodule Auth.Router do
  use Auth.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Auth do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/registrations", RegistrationController, only: [:new, :create]
   get    "/login",  SessionController, :new
   post   "/login",  SessionController, :create
   delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Auth do
  #   pipe_through :api
  # end
end

web/models/registration.ex
defmodule Auth.Registration do
  import Ecto.Changeset, only: [put_change: 3]

  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hashed_password(changeset.params["password"]))
    |> repo.insert()
  end

  defp hashed_password(password) do
    # hash password
    Comeonin.Bcrypt.hashpwsalt(password)
  end
end

web/models/session.ex
defmodule Auth.Session do
  alias Auth.User
  alias Auth.Repo

  def login(params, repo) do
    user = repo.get_by(User, email: String.downcase(params["email"]))
    case authenticate(user, params["password"]) do
      true -> {:ok, user}
      _    -> :error
    end
  end

  defp authenticate(user, password) do
    case user do
      nil -> false
      _   -> Comeonin.Bcrypt.checkpw(password, user.crypted_password)
    end
  end

def current_user(conn) do
  id = Plug.Conn.get_session(conn, :current_user)
  if id, do: Repo.get(User, id)
end

def logged_in?(conn), do: !!current_user(conn)

end

web/models/user.ex
defmodule Auth.User do
  use Auth.Web, :model

  schema "users" do
    field :email, :string
    field :crypted_password, :string
    field :password, :string, virtual: true

    timestamps
  end

  @required_fields ~w(email password)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:email)
    #|> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 5)
  end

end

web/controllers/page_controller.ex
defmodule Auth.PageController do
  use Auth.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/registration_controller.ex
defmodule Auth.RegistrationController do
  use Auth.Web, :controller
  alias Auth.User

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, changeset: changeset
  end

def create(conn, %{"user" => user_params}) do
  changeset = User.changeset(%User{}, user_params)

  case Auth.Registration.create(changeset, Auth.Repo) do
    {:ok, changeset} ->
      conn
#      |> put_session(:current_user, user.id)
      |> put_flash(:info, "Your account was created")
      |> redirect(to: "/")
    {:error, changeset} ->
      conn
      |> put_flash(:info, "Unable to create account")
      |> render("new.html", changeset: changeset)
  end
end

end

web/controllers/session_controller.ex
import Joken

defmodule Auth.SessionController do
  use Auth.Web, :controller

  def new(conn, _params) do
    render conn, "new.html"
  end

def create(conn, %{"session" => session_params}) do
  case Auth.Session.login(session_params, Auth.Repo) do
    {:ok, user} ->
      my_token = %{user_id: user.email}
      |> token
      |> with_validation("user_id", &(&1 == 1))
      |> with_signer(hs256("53F61451CAD6231FDCF6859C6D5B88C1EBD5DC38B9F7EBD990FADD4EB8EB9063"))
      |> sign
      |> get_compact

      conn
      |> put_session(:token, my_token)
      |> put_session(:current_user, user.id)
      |> put_session(:current_email, user.email)
      |> put_flash(:info, "Logged in")
      |> redirect(to: "/")
    :error ->
      conn
      |> put_flash(:info, "Wrong email or password")
      |> render("new.html")
  end
end

def delete(conn, _) do
  conn
  |> delete_session(:current_user)
  |> put_flash(:info, "Logged out")
  |> redirect(to: "/")
end

end

web/views/error_view.ex
defmodule Auth.ErrorView do
  use Auth.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Auth.LayoutView do
  use Auth.Web, :view
end

web/views/page_view.ex
defmodule Auth.PageView do
  use Auth.Web, :view
end

web/views/registration_view.ex
defmodule Auth.RegistrationView do
  use Auth.Web, :view
end

web/views/session_view.ex
defmodule Auth.SessionView do
  use Auth.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/style.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
<%= if logged_in?(@conn) do %>
  <li><%= current_user(@conn).email %></li>
  <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Login",    to: "/login" %></li>
  <li><%= link "Register", to: registration_path(@conn, :new) %></li>
<% end %>
        </ul>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<input type='text' id='to' size="20" placeholder="to">
<input type='text' id='message' size="20" placeholder="message">
<input type='button' id='send' value='send' onclick='sendMessage()'>
<br/><br/>
<div class="jumbotron">
  <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js'></script>
  <script>var JWT = '<%= Plug.Conn.get_session(@conn, :token) %>';var USER = '<%= Plug.Conn.get_session(@conn, :current_email) %>@alchemy.local';</script>
  <script src='<%= static_path(@conn, "/js/strophe.min.js") %>'></script>
  <script src='<%= static_path(@conn, "/js/chat.js") %>'></script>

  <div id='log'></div>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/session/new.html.eex
<h2>Login</h2>

<%= form_for @conn, session_path(@conn, :create), [name: :session], fn f -> %>
  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>